### ISSUE TITLE
Интеграция перестала работать после апгрейда HACS на версию 1.11.3

### ISSUE THREAD

**Issue by IgorAga** [alryaz/hass-mosenergosbyt#10]
2021-02-15 16:50:04 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mosenergosbyt platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/homeassistant/.homeassistant/custom_components/mosenergosbyt/sensor.py", line 482, in async_setup_entry
    result = await update_call()
  File "/home/homeassistant/.homeassistant/custom_components/mosenergosbyt/sensor.py", line 146, in _entity_updater
    meters = await account.get_meters()
  File "/home/homeassistant/.homeassistant/custom_components/mosenergosbyt/mosenergosbyt.py", line 740, in get_meters
    indications = await self.get_last_indications()
  File "/home/homeassistant/.homeassistant/custom_components/mosenergosbyt/mosenergosbyt.py", line 762, in get_last_indications
    indications = await self._get_indications(previous_month_start, now)
  File "/home/homeassistant/.homeassistant/custom_components/mosenergosbyt/mosenergosbyt.py", line 734, in _get_indications
    return [
  File "/home/homeassistant/.homeassistant/custom_components/mosenergosbyt/mosenergosbyt.py", line 736, in <listcomp>
    for invoice_group in response['data'] for invoice in invoice_group['child']
KeyError: 'child'

**Comment by varakirill** [comment]
Точно такая же проблема - установка интеграции с авторизацией происходит  нормально, но ни устройств, ни объектов нет, в логе - точно такая же ошибка как и выше.

**Comment by alryaz** [comment]
~~Пожалуйста, напишите в Telegram https://tg-me.ru/alryaz (у меня, к сожалению, не на чем тестировать, так как сам не пользователь Мособлгаза), сегодня проверю.~~

Edit: перепутал репозитории; начинаю проверку.

**Comment by alryaz** [comment]
@varakirill , @IgorAga , прошу проверить тег v0.2.9. Небольшой обходной трюк выполнен.

**Comment by varakirill** [comment]
> @varakirill , @IgorAga , прошу проверить тег v0.2.9. Небольшой обходной трюк выполнен.

Обновил, перезагрузил НА, удалил интеграцию, перезагрузил НА, добавил интеграцию, перезагрузил НА... Все равно:

Logger: homeassistant.components.sensor
Source: custom_components/mosenergosbyt/mosenergosbyt.py:717
Integration: Сенсор (documentation, issues)
First occurred: 10:17:15 (1 occurrences)
Last logged: 10:17:15
Error while setting up mosenergosbyt platform for sensorTraceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/mosenergosbyt/sensor.py", line 490, in async_setup_entry result = await update_call() File "/config/custom_components/mosenergosbyt/sensor.py", line 202, in _entity_updater invoice = await account.get_last_invoice() File "/config/custom_components/mosenergosbyt/mosenergosbyt.py", line 466, in get_last_invoice invoices = await self._get_invoices(previous_month_start, now) File "/config/custom_components/mosenergosbyt/mosenergosbyt.py", line 701, in _get_invoices return [Invoice( File "/config/custom_components/mosenergosbyt/mosenergosbyt.py", line 717, in <listcomp> for invoice_group in response['data'] for invoice in invoice_group['child']] KeyError: 'child'

**Comment by alryaz** [comment]
@varakirill , напишите, пожалуйста, в Telegram https://tg-me.ru/alryaz

**Comment by varakirill** [comment]
> @varakirill , напишите, пожалуйста, в Telegram https://tg-me.ru/alryaz

Уже хотел написать, но решил сначала попробовать коммит - все заработало, спасибо!
