### ISSUE TITLE
Ошибки после обновления на 0.3.0

### ISSUE THREAD

**Issue by bastshoes** [alryaz/hass-mosenergosbyt#12]
Обновился до 0.3.0. 

При запуске интеграции возникает ошибка 

Error while setting up mosenergosbyt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mosenergosbyt/sensor.py", line 468, in async_setup_entry
    await async_discover(
  File "/config/custom_components/mosenergosbyt/sensor.py", line 439, in async_discover
    entities, tasks = task.result()
  File "/config/custom_components/mosenergosbyt/sensor.py", line 335, in async_discover_meters
    entities, tasks = await _common_discover_entities(
  File "/config/custom_components/mosenergosbyt/sensor.py", line 237, in _common_discover_entities
    identifier = object_code_getter(iter_object)
  File "/config/custom_components/mosenergosbyt/sensor.py", line 340, in <lambda>
    object_code_getter=lambda x: x.meter_code,
  File "/config/custom_components/mosenergosbyt/api.py", line 1568, in meter_code
    return self._data['nm_counter']
KeyError: 'nm_counter'

**Comment by alryaz** [comment]
Исправлено в v0.3.1
