### ISSUE TITLE
Постоянно сыпятся ошибки...

### ISSUE THREAD

**Issue by Aldaran** [alryaz/hass-mosenergosbyt#13]
Error while setting up mosenergosbyt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mosenergosbyt/sensor.py", line 468, in async_setup_entry
    await async_discover(
  File "/config/custom_components/mosenergosbyt/sensor.py", line 439, in async_discover
    entities, tasks = task.result()
  File "/config/custom_components/mosenergosbyt/sensor.py", line 335, in async_discover_meters
    entities, tasks = await _common_discover_entities(
  File "/config/custom_components/mosenergosbyt/sensor.py", line 243, in _common_discover_entities
    '*' + identifier[-5:]
TypeError: 'NoneType' object is not subscriptable

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mosenergosbyt/sensor.py", line 619, in _update_entity
    self.async_schedule_update_ha_state(force_refresh=True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 489, in async_schedule_update_ha_state
    self.hass.async_create_task(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'async_create_task'

**Comment by MaximSN** [comment]
Аналогичная проблема. с Апреля 2021 наша УК передала дом на обслуживание в МосЭнергосбыт(МосОблЕИРЦ),
при включении интеграции счета видны в настройках, а датчики не нашлись.
Ошибки такие же как выше
![image](https://user-images.githubusercontent.com/57829001/117995135-bffdd500-b349-11eb-950b-1fc57439e1dd.png)

**Comment by Aldaran** [comment]
У меня кстати нет настроек ui, доступны настройки только через yaml... Через интеграции могу только добавить учетные записи.

**Comment by rs-afrolov** [comment]
У меня сенсоры mes_meter на прошлой неделе корректно возвращали данные (лицевые счета в МосОблЕИРЦ). Сейчас все сенсоры mes_meter стали unavailable:
![image](https://user-images.githubusercontent.com/1677189/118048103-77174200-b384-11eb-83b1-017ec869cd20.png)
Сенсоры mes_account данные возвращают.
Сенсоры mes_invoice возвращают данные платежек прошлого месяца, хотя в ЛК Мосэнергосбыт с начала текущей недели видны новые платежки.

За последние дни несколько раз обновился Home assistant core (сейчас установлен core-2021.5.3), HACS 1.12.3
Add-on Мосэнергосбыт установлен через HACS (v0.3.1). Пробовал его переустанавливать - не помогло.

**Comment by alryaz** [comment]
> У меня кстати нет настроек ui, доступны настройки только через yaml... Через интеграции могу только добавить учетные записи.

@Aldaran Настройки ("Опции") - это отдельное меню, доступное уже после добавления конкретной интеграции.\

> Аналогичная проблема. с Апреля 2021 наша УК передала дом на обслуживание в МосЭнергосбыт(МосОблЕИРЦ),
при включении интеграции счета видны в настройках, а датчики не нашлись.

@MaximSN Пожалуйста, проверьте релиз v0.3.2; если проблему он не исправит, напишите, пожалуйста, в Telegram (никнейм alryaz)

> У меня сенсоры mes_meter на прошлой неделе корректно возвращали данные (лицевые счета в МосОблЕИРЦ). Сейчас все сенсоры mes_meter стали unavailable:

@rs-afrolov Напишите, пожалуйста, в Telegram (никнейм alryaz)

**Comment by Aldaran** [comment]
После обновления почти все ошибки ушли... Осталось такое:
2021-05-26 23:17:51 ERROR (MainThread) [homeassistant.components.sensor] Platform mosenergosbyt does not generate unique IDs. ID meter_36427737 already exists - ignoring sensor.mes_meter_36427737

PS. Спасибо за Ваш труд.

Прошло 10 дней... и началось:

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mosenergosbyt/sensor.py", line 631, in _update_entity
    self.async_schedule_update_ha_state(force_refresh=True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 489, in async_schedule_update_ha_state
    self.hass.async_create_task(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'async_create_task'

**Comment by alryaz** [comment]
Данная проблема технически будет решена в аналогичной интеграции (см. README.md). Закрываю в связи с переносом репозитория.
