### ISSUE TITLE
Сенсор счетчика unavailable

### ISSUE THREAD

**Issue by bastshoes** [alryaz/hass-mosenergosbyt#3]
При создании сенсора счетчика возникают ошибки:

№1:

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/mosenergosbyt/sensor.py", line 565, in async_update
    for i, value in enumerate(self.meter.submitted_indications, start=1):
TypeError: 'NoneType' object is not iterable

№2:

Error while setting up mosenergosbyt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 443, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 324, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/mosenergosbyt/sensor.py", line 449, in device_state_attributes
    return {**self._attributes, ATTR_ATTRIBUTION: ATTRIBUTION}
TypeError: 'NoneType' object is not a mapping

**Comment by kcinIvan** [comment]
Сегодня поставил через hacs, то же самое.
![Screenshot_Home_Assistant_20200624-203426](https://user-images.githubusercontent.com/28870337/85604735-3cb49180-b65a-11ea-9662-e54d3acce5fd.png)

**Comment by alryaz** [comment]
Немного разные проблемы, попробую найти решение. Если проблемы не исчезли ещё, пожалуйста, напишите в Telegram (@alryaz). Требуется отследить запросы, и чем они отличаются результатами от моих тестовых.

**Comment by kcinIvan** [comment]
Проблема исчезла.
А этом сенсоре тарифов не должно быть?

**Comment by alryaz** [comment]
@kcinIvan вообще, нет (https://github.com/alryaz/hass-mosenergosbyt/blob/162cf04c059fc6eeedfab25f261706d10497912f/custom_components/mosenergosbyt/sensor.py#L607), но давайте добавлю 👍
